default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: <%= ENV['POSTGRES_HOST'] %>
  port: <%= ENV['POSTGRES_PORT'] %>

development:
  <<: *default
  database: EcommerceApp_development

test:
  <<: *default
  database: EcommerceApp_test

production:
  <<: *default
  database: EcommerceApp_production
  username: pguser
  password: <%= ENV['POSTGRES_PASSWORD'] %>